use crate::director::Storyboard;
use crate::models::sd15::SD15;
use anyhow::Result;
use std::sync::{Arc, Mutex};

/// Cinematographer generates manga panels using Stable Diffusion (Candle).
pub struct Cinematographer {
    sd_model: Arc<Mutex<SD15>>, // Mutex needed because SD15.text_to_image requires &mut self (for Scheduler)
}

impl Cinematographer {
    pub fn new(sd_model: Arc<Mutex<SD15>>) -> Self {
        Self { sd_model }
    }

    /// Generate static manga panels for all shots
    pub async fn shoot(&self, storyboard: &mut Storyboard, style: &str) -> Result<()> {
        let output_dir = std::path::Path::new("output/images");
        if !output_dir.exists() {
            std::fs::create_dir_all(output_dir)?;
        }

        // === CONSISTENCY STRATEGY ===
        // Use the SAME seed for ALL panels to maximize character consistency
        // Changed to 123: A classic, stable seed for testing.
        let consistent_seed: u64 = 123;

        // Dynamic Style Prompt - SIMPLIFIED
        let style_prompt = match style {
            "manga" => "monochrome manga style, japanese manga, black and white, lineart, highly detailed, screentone, flat color",
            "anime" => "anime style, vivid colors, cel shaded, kyoto animation, high quality, 2D",
            "ghibli" | _ => "ghibli style, anime, studio ghibli, painting, highly detailed, vivid colors, masterpiece, best quality, flat color",
        };

        // Negative prompt (shared) - STANDARD
        let negative_prompt = "photorealistic, realism, 3d, realistic, real world, photograph, photography, camera, blurry, low quality, distorted, ugly, bad anatomy, watermark, text, bad hand, mutation, deformed, extra limbs, multiple views, multiple people";

        // === GPU WARMUP REMOVED ===
        // We are using CPU now for stability.
        println!("⏩ Skipping GPU warmup (CPU mode active)...");

        for shot in &mut storyboard.shots {
            println!(
                "🎬 Drawing Panel: {} (Character: {})",
                shot.panel_name, shot.character
            );

            // Trust the visual_prompt coming from the AI Script pipeline
            // It is now generated by a dedicated translation pass + mood injection
            // We FORCE `(1girl, solo:1.5)` to start to fix blobs/missing chars.
            // We FORCE `(black hair, blue eyes:1.2)` and `indoors` to ensure consistency.
            // We REMOVED mood tags here to simplify the prompt and avoid "Peaceful" crashing Panel 1.
            let full_prompt = format!(
                "(1girl, solo:1.5), (black hair, blue eyes:1.2), {}, {}, indoors, cluttered workshop, 2D",
                style_prompt, shot.visual_prompt
            );

            // Strip any double quotes from the prompt to avoid confusing the tokenizer
            let full_prompt = full_prompt.replace('"', "").replace('\'', "");

            println!("  🎨 Prompt: {}", full_prompt);

            // Output path for this shot's image
            let image_filename = format!("shot_{}.png", shot.id);
            let image_path = output_dir.join(&image_filename);

            // Generate Image using SD15 — SAME SEED for consistency
            println!("  🖍️ Generating image (Seed: {})...", consistent_seed);

            // Using 512x512 SQUARE resolution to ensure memory alignment stability on CPU
            let image = {
                let mut sd = self.sd_model.lock().unwrap();
                sd.text_to_image(
                    &full_prompt,
                    negative_prompt,
                    512, // Width (Square 512)
                    512, // Height (Square 512)
                    25,  // Steps
                    7.5, // CFG Scale
                    consistent_seed,
                )?
            };

            // Save image
            image.save(&image_path)?;

            // Update storyboard with image path
            let abs_path = image_path.canonicalize().unwrap_or(image_path.clone());
            shot.image_paths = vec![abs_path];
            shot.video_path = None;

            println!("  ✅ Image saved: {:?}", image_path);
        }

        println!("📸 All panels drawn!");
        Ok(())
    }
}
